// Generated by scripts/build-moved.mjs
(async () => {
  const TO = "https://overlap.runtianwu.com";
  const remembered = {};
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('overlap.')) remembered[key] = localStorage.getItem(key);
    }
  } catch { /* storage blocked: move without it */ }
  let hash = location.hash.slice(1).replace(/(?:^|&)moved=[^&]*/g, '').replace(/^&/, '');
  if (Object.keys(remembered).length) {
    try {
      const moved = await encode(JSON.stringify(remembered));
      hash = hash ? hash + '&moved=' + moved : 'moved=' + moved;
    } catch { /* move without it */ }
  }
  const target = TO + location.pathname + location.search + (hash ? '#' + hash : '');
  const link = document.getElementById('to');
  if (link) link.href = target;
  location.replace(target);
})();

async function encode(text) {
  let bytes = new TextEncoder().encode(text);
  let tag = 'j';
  if (typeof CompressionStream === 'function') {
    const stream = new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate-raw'));
    bytes = new Uint8Array(await new Response(stream).arrayBuffer());
    tag = 'z';
  }
  let bin = '';
  for (let i = 0; i < bytes.length; i += 0x8000) bin += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000));
  return tag + btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
