// Generated by `npm run i18n:merge`. The server's copy of every language (for emails).
import en from './en.js';
import es from './es.js';
import fr from './fr.js';
import de from './de.js';
import it from './it.js';
import pt from './pt.js';
import nl from './nl.js';
import pl from './pl.js';
import ru from './ru.js';
import uk from './uk.js';
import tr from './tr.js';
import ar from './ar.js';
import hi from './hi.js';
import zh_Hans from './zh-Hans.js';
import zh_Hant from './zh-Hant.js';
import ja from './ja.js';
import ko from './ko.js';
import vi from './vi.js';
import id from './id.js';
import th from './th.js';

export default { 'en': en, 'es': es, 'fr': fr, 'de': de, 'it': it, 'pt': pt, 'nl': nl, 'pl': pl, 'ru': ru, 'uk': uk, 'tr': tr, 'ar': ar, 'hi': hi, 'zh-Hans': zh_Hans, 'zh-Hant': zh_Hant, 'ja': ja, 'ko': ko, 'vi': vi, 'id': id, 'th': th };
